# Generated by Django 4.2.11 on 2024-04-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
