# Generated by Django 4.2.11 on 2024-04-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_machineparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineParametersGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_count', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.machineparameters')),
            ],
        ),
    ]
