# Generated by Django 4.2.11 on 2024-05-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_machineparametersgraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='alerts',
            table='Alerts',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
        migrations.AlterModelTable(
            name='defects',
            table='Defects',
        ),
        migrations.AlterModelTable(
            name='machineparameters',
            table='MachineParameters',
        ),
        migrations.AlterModelTable(
            name='machineparametersgraph',
            table='MachineParametersGraph',
        ),
        migrations.AlterModelTable(
            name='machines',
            table='Machines',
        ),
        migrations.AlterModelTable(
            name='machinetemperatures',
            table='MachineTemperatures',
        ),
        migrations.AlterModelTable(
            name='reports',
            table='Reports',
        ),
    ]
