# Generated by Django 4.2.11 on 2024-06-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_customuser_options_alter_alerts_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.CharField(max_length=250)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.defects')),
            ],
            options={
                'db_table': 'DefectNotification',
            },
        ),
    ]
