# Generated by Django 4.2.11 on 2024-04-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alerts_defects_department_machines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defects',
            name='color_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
